#MAPS SUPER-ENHANCERS USING REGIONS DEFINED BY HG18_MM1S_MED1.gff AND RANKING BY MED1 ChIP-SEQ SIGNAL FROM MM1S_MED1.hg18.bwt.sorted.bam CHIP-SEQ SIGNAL WITH BACKGROUND CORRECTION FROM MM1S_WCE.hg18.bwt.sorted.bam

export PATH=$PATH:$HOME/github/rose/
python2 $(which ROSE_main.py) -g HG18 -i ./data/HG18_MM1S_MED1.gff -r ./data/MM1S_MED1.hg18.bwt.sorted.bam -c ./data/MM1S_WCE.hg18.bwt.sorted.bam -o example -s 12500 -t 2500


#MAPS SUPER-ENHANCERS USING 1000 REGIONS DEFINED BY HG18_MM1S_MED1.gff AND RANKING BY MED1 ChIP-SEQ SIGNAL FROM MM1S_MED1.hg18.bwt.sorted.bam CHIP-SEQ SIGNAL WITHOUT BACKGROUND CORRECTION
#MUCH FASTER PROGRAM CALL FOR BENCHMARKING AND TESTING
#python mapEnhancerFromFactor.py -g HG18 -i ./data/HG18_MM1S_MED1.gff -r ./data/MM1S_MED1.hg18.bwt.sorted.bam -o example_test -s 12500 -t 2500
